name: merge-package-build
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

defaults:
  run:
    shell: 'sh -e {0}'

jobs:
  build:
    name: Build check
    runs-on: ubuntu-latest
    if: github.base_ref == 'staging' && !startsWith(github.ref, 'refs/heads/release/')
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Build package
        run: make
      -
        name: Update digests
        run: make digests > digests.txt
      -
        name: Show diff
        run: git diff
